# preprocessing 
dataset_info_path: dataset/dataset_info.json # for preprocessed data description

# arguments for dataset
num_workers: 2
dataset_output_size: [64,144,144]
data_window_level: [-500,500]

# arguments for training
is_dynamic_empty_cache: true
is_amp_train: true
use_tqdm: true
epochs: 1000
batch_size: 1
lr: 0.01
conf_thresh: 0.95

# train status
pretrained_model_path: exp/supervised_unet/lab_01/best.pth0

# net
nclass: 14
class_name_list: [
liver Dice,
right kidney Dice,
spleen Dice,
pancreas Dice,
aorta Dice,
inferior vena cava Dice,
right adrenal gland Dice,
left adrenal gland Dice,
gallbladder Dice,
esophagus Dice,
stomach Dice,
duodenum Dice,
left kidney Dice
]

feature_chns: [32, 64, 64, 128, 256]
dropout: [0.05, 0.1, 0.2, 0.3, 0.5]