# output args
output_dir_root: exp
project_name: unimatch_unet_3d
train_name: flare22
# preprocessing 
dataset_info_path: dataset/flare/dataset_info.json # for preprocessed data description

# arguments for dataset
num_workers: 2
dataset_output_size: [48,192,192]
data_window_level: [-500,500]

# net
nclass: 14
class_name_list: [
liver Dice,
right kidney Dice,
spleen Dice,
pancreas Dice,
aorta Dice,
inferior vena cava Dice,
right adrenal gland Dice,
left adrenal gland Dice,
gallbladder Dice,
esophagus Dice,
stomach Dice,
duodenum Dice,
left kidney Dice
]

feature_chns: [16, 32, 64, 128, 256]
dropout: [0.05, 0.1, 0.2, 0.3, 0.5]
# arguments for training
epochs: 500
batch_size: 2 # per GPU x 1 GPU
lr: 0.01
conf_thresh: 0.95
